# Generated by Django 4.1.7 on 2023-03-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='grivance',
            field=models.TextField(null=True),
        ),
    ]
